### ISSUE TITLE
ImportError: cannot import name 'EFBChannel' from 'ehforwarderbot' after running wizard

### ISSUE THREAD

**Issue by armFusion** [ehForwarderBot/ehForwarderBot#240]
**Describe the bug**  
after running `efb-wizard` or `ehforwarderbot` or `python3 -m ehforwarderbot`:
```
Traceback (most recent call last):
  File "/usr/local/bin/efb-wizard", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ehforwarderbot/wizard.py", line 609, in main
    data.load_config()
  File "/usr/local/lib/python3.7/site-packages/ehforwarderbot/wizard.py", line 108, in load_config
    self.load_modules_list()
  File "/usr/local/lib/python3.7/site-packages/ehforwarderbot/wizard.py", line 120, in load_modules_list
    cls = i.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2446, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2452, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/__init__.py", line 21, in <module>
    from ehforwarderbot import EFBChannel, EFBMsg, EFBStatus, coordinator, EFBChat
ImportError: cannot import name 'EFBChannel' from 'ehforwarderbot' (/usr/local/lib/python3.7/site-packages/ehforwarderbot/__init__.py)
```
**Version information (please complete the following information):**  
- OS: macOS 10.14.6
- Detailed Python, EFB and module versions: (you can obtain this by running `ehforwarderbot --version`)

```
EH Forwarder Bot
Version: 2.1.0
Python version:
3.7.7 [Clang 11.0.0 (clang-1100.0.33.17)]
```

**Comment by blueset** [comment]
Please try upgrade `efb-telegram-master` to the latest stable version (2.2.2). If you have any other modules released before January 2020, please update them as well.

**Comment by blueset** [comment]
Closed for stale.
